---

- name: Generate DHCPD Config for ZTP
  hosts: dhcpd
  connection: local
  gather_facts: no

  tasks:

  - name: Create Directory to store dhcpd.conf file
    file: path=./dhcpd/ state=directory
 
  - name: Create dhcpd.conf file
    template: src=templates/dhcpd.j2 dest=./dhcpd/dhcpd.conf

  #- debug: var=vars
