---

- name: Generate DHCPD Config for ZTP
  hosts: dhcpd
  connection: local
  gather_facts: no

  tasks:

  - name: Create dhcpd.conf file
    template: src=test.j2 dest=test.conf

  #- debug: var=vars
